# permissions for end users to view passwords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: password-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: password-operator
    app.kubernetes.io/part-of: password-operator
    app.kubernetes.io/managed-by: kustomize
  name: password-viewer-role
rules:
- apiGroups:
  - secret.example.com
  resources:
  - passwords
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secret.example.com
  resources:
  - passwords/status
  verbs:
  - get
