---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - secret.example.com
  resources:
  - passwords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret.example.com
  resources:
  - passwords/finalizers
  verbs:
  - update
- apiGroups:
  - secret.example.com
  resources:
  - passwords/status
  verbs:
  - get
  - patch
  - update
