name: check-kubebuilder-release

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check
        run: |
          latest_version=$(curl --silent "https://api.github.com/repos/kubernetes-sigs/kubebuilder/releases" | jq -r '.[].tag_name' | head -n 1)
          if [ $(grep kubebuilder README.md | grep -c $latest_version) = "1" ]; then
            echo 'latest'
          else
            echo 'new release exists'
          fi
